spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
    open-in-view: false

  h2:
    console:
      enabled: false

storage:
  datasource:
    core:
      driver-class-name: org.postgresql.Driver
      jdbc-url:
      username:
      password:
      pool-name:
      data-source-properties:
        rewriteBatchedStatements: true