spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
  h2:
    console:
      enabled: true

storage:
  datasource:
    core:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:55000/simple_blog?useSSL=false&serverTimezone=Asia/Seoul
      username: admin
      password: cosmos
      pool-name: core-db-pool
      data-source-properties:
        rewriteBatchedStatements: true